import '../models/mail_model.dart';

List<MailModel> mailList = [
  MailModel(
    "Kevin Powell",
    "Day 8 - Conquering Responsive Layouts",
    "Hey there, \nWelcome to week 2 of Conquering Responsive Layouts! \nAs I mentioned at the end of week 1, what we covered was absolutely essential to understanding how to create responsive layouts. \n\nNow that we're getting more comfortable creating simple layouts that can adapt to any screen size (to a certain extent), it's time to up our game a little bit, and flexbox is the next key ingredient we are going to add to our arsenal! \n\nThis week, we'll be taking our layout, adding some new sections and a navigation to it, and using those things to help us really understand how flexbox works both in building out individual components as well bigger picture layouts. \n\nClick here to access today's lessons. \n\nKevin \n\nP.S. This week, the pace will be a little faster. If ever you feel like you're falling behind, please take it at your own pace and make sure you understand how things are working. The content of this course will be available to you forever!",
    "22:46",
    false,
    false,
  ),
  MailModel(
    "Yusuf Karahocagil (Jira)",
    "[JIRA] (WEB-35) Responsive olarak login, register, şifremi unuttum, kullanıcı profili, kullanıcı listesi, kullanıcı mail listesi yapımı",
    "Yusuf Karahocagil bir güncelleme yaptı. \n\nWebLessons	  /  	WEB-35 \n\nResponsive olarak login, register, şifremi unuttum, kullanıcı profili, kullanıcı listesi, kullanıcı mail listesi yapımı",
    "22:11",
    true,
    false,
  ),
  MailModel(
    "Xiaomi Corporation",
    "Mi Account verification code",
    "Hi mktorunoglu55@gmail.com! \n\nYour Mi Account 61*****185 verification code is 844155. Don't show this code to other people. If you didn't request the code, go to id.mi.com and change your password immediately. This message was generated automatically. Don't reply to this message. \n\nMi Account team",
    "20:02",
    true,
    true,
  ),
  MailModel(
    "Kevin Powell",
    "Day 8 - Conquering Responsive Layouts",
    "Hey there, \nWelcome to week 2 of Conquering Responsive Layouts! \nAs I mentioned at the end of week 1, what we covered was absolutely essential to understanding how to create responsive layouts. \n\nNow that we're getting more comfortable creating simple layouts that can adapt to any screen size (to a certain extent), it's time to up our game a little bit, and flexbox is the next key ingredient we are going to add to our arsenal! \n\nThis week, we'll be taking our layout, adding some new sections and a navigation to it, and using those things to help us really understand how flexbox works both in building out individual components as well bigger picture layouts. \n\nClick here to access today's lessons. \n\nKevin \n\nP.S. This week, the pace will be a little faster. If ever you feel like you're falling behind, please take it at your own pace and make sure you understand how things are working. The content of this course will be available to you forever!",
    "22:46",
    false,
    false,
  ),
  MailModel(
    "Kevin Powell",
    "Day 8 - Conquering Responsive Layouts",
    "Hey there, \nWelcome to week 2 of Conquering Responsive Layouts! \nAs I mentioned at the end of week 1, what we covered was absolutely essential to understanding how to create responsive layouts. \n\nNow that we're getting more comfortable creating simple layouts that can adapt to any screen size (to a certain extent), it's time to up our game a little bit, and flexbox is the next key ingredient we are going to add to our arsenal! \n\nThis week, we'll be taking our layout, adding some new sections and a navigation to it, and using those things to help us really understand how flexbox works both in building out individual components as well bigger picture layouts. \n\nClick here to access today's lessons. \n\nKevin \n\nP.S. This week, the pace will be a little faster. If ever you feel like you're falling behind, please take it at your own pace and make sure you understand how things are working. The content of this course will be available to you forever!",
    "22:46",
    false,
    false,
  ),
  MailModel(
    "Xiaomi Corporation",
    "Mi Account verification code",
    "Hi mktorunoglu55@gmail.com! \n\nYour Mi Account 61*****185 verification code is 844155. Don't show this code to other people. If you didn't request the code, go to id.mi.com and change your password immediately. This message was generated automatically. Don't reply to this message. \n\nMi Account team",
    "20:02",
    true,
    true,
  ),
  MailModel(
    "Kevin Powell",
    "Day 8 - Conquering Responsive Layouts",
    "Hey there, \nWelcome to week 2 of Conquering Responsive Layouts! \nAs I mentioned at the end of week 1, what we covered was absolutely essential to understanding how to create responsive layouts. \n\nNow that we're getting more comfortable creating simple layouts that can adapt to any screen size (to a certain extent), it's time to up our game a little bit, and flexbox is the next key ingredient we are going to add to our arsenal! \n\nThis week, we'll be taking our layout, adding some new sections and a navigation to it, and using those things to help us really understand how flexbox works both in building out individual components as well bigger picture layouts. \n\nClick here to access today's lessons. \n\nKevin \n\nP.S. This week, the pace will be a little faster. If ever you feel like you're falling behind, please take it at your own pace and make sure you understand how things are working. The content of this course will be available to you forever!",
    "22:46",
    false,
    false,
  ),
  MailModel(
    "Yusuf Karahocagil (Jira)",
    "[JIRA] (WEB-35) Responsive olarak login, register, şifremi unuttum, kullanıcı profili, kullanıcı listesi, kullanıcı mail listesi yapımı",
    "Yusuf Karahocagil bir güncelleme yaptı. \n\nWebLessons	  /  	WEB-35 \n\nResponsive olarak login, register, şifremi unuttum, kullanıcı profili, kullanıcı listesi, kullanıcı mail listesi yapımı",
    "22:11",
    true,
    false,
  ),
  MailModel(
    "Yusuf Karahocagil (Jira)",
    "[JIRA] (WEB-35) Responsive olarak login, register, şifremi unuttum, kullanıcı profili, kullanıcı listesi, kullanıcı mail listesi yapımı",
    "Yusuf Karahocagil bir güncelleme yaptı. \n\nWebLessons	  /  	WEB-35 \n\nResponsive olarak login, register, şifremi unuttum, kullanıcı profili, kullanıcı listesi, kullanıcı mail listesi yapımı",
    "22:11",
    true,
    false,
  ),
  MailModel(
    "Xiaomi Corporation",
    "Mi Account verification code",
    "Hi mktorunoglu55@gmail.com! \n\nYour Mi Account 61*****185 verification code is 844155. Don't show this code to other people. If you didn't request the code, go to id.mi.com and change your password immediately. This message was generated automatically. Don't reply to this message. \n\nMi Account team",
    "20:02",
    true,
    true,
  ),
  MailModel(
    "Kevin Powell",
    "Day 8 - Conquering Responsive Layouts",
    "Hey there, \nWelcome to week 2 of Conquering Responsive Layouts! \nAs I mentioned at the end of week 1, what we covered was absolutely essential to understanding how to create responsive layouts. \n\nNow that we're getting more comfortable creating simple layouts that can adapt to any screen size (to a certain extent), it's time to up our game a little bit, and flexbox is the next key ingredient we are going to add to our arsenal! \n\nThis week, we'll be taking our layout, adding some new sections and a navigation to it, and using those things to help us really understand how flexbox works both in building out individual components as well bigger picture layouts. \n\nClick here to access today's lessons. \n\nKevin \n\nP.S. This week, the pace will be a little faster. If ever you feel like you're falling behind, please take it at your own pace and make sure you understand how things are working. The content of this course will be available to you forever!",
    "22:46",
    false,
    false,
  ),
  MailModel(
    "Yusuf Karahocagil (Jira)",
    "[JIRA] (WEB-35) Responsive olarak login, register, şifremi unuttum, kullanıcı profili, kullanıcı listesi, kullanıcı mail listesi yapımı",
    "Yusuf Karahocagil bir güncelleme yaptı. \n\nWebLessons	  /  	WEB-35 \n\nResponsive olarak login, register, şifremi unuttum, kullanıcı profili, kullanıcı listesi, kullanıcı mail listesi yapımı",
    "22:11",
    true,
    false,
  ),
  MailModel(
    "Xiaomi Corporation",
    "Mi Account verification code",
    "Hi mktorunoglu55@gmail.com! \n\nYour Mi Account 61*****185 verification code is 844155. Don't show this code to other people. If you didn't request the code, go to id.mi.com and change your password immediately. This message was generated automatically. Don't reply to this message. \n\nMi Account team",
    "20:02",
    true,
    true,
  ),
  MailModel(
    "Xiaomi Corporation",
    "Mi Account verification code",
    "Hi mktorunoglu55@gmail.com! \n\nYour Mi Account 61*****185 verification code is 844155. Don't show this code to other people. If you didn't request the code, go to id.mi.com and change your password immediately. This message was generated automatically. Don't reply to this message. \n\nMi Account team",
    "20:02",
    true,
    true,
  ),
  MailModel(
    "Kevin Powell",
    "Day 8 - Conquering Responsive Layouts",
    "Hey there, \nWelcome to week 2 of Conquering Responsive Layouts! \nAs I mentioned at the end of week 1, what we covered was absolutely essential to understanding how to create responsive layouts. \n\nNow that we're getting more comfortable creating simple layouts that can adapt to any screen size (to a certain extent), it's time to up our game a little bit, and flexbox is the next key ingredient we are going to add to our arsenal! \n\nThis week, we'll be taking our layout, adding some new sections and a navigation to it, and using those things to help us really understand how flexbox works both in building out individual components as well bigger picture layouts. \n\nClick here to access today's lessons. \n\nKevin \n\nP.S. This week, the pace will be a little faster. If ever you feel like you're falling behind, please take it at your own pace and make sure you understand how things are working. The content of this course will be available to you forever!",
    "22:46",
    false,
    false,
  ),
  MailModel(
    "Yusuf Karahocagil (Jira)",
    "[JIRA] (WEB-35) Responsive olarak login, register, şifremi unuttum, kullanıcı profili, kullanıcı listesi, kullanıcı mail listesi yapımı",
    "Yusuf Karahocagil bir güncelleme yaptı. \n\nWebLessons	  /  	WEB-35 \n\nResponsive olarak login, register, şifremi unuttum, kullanıcı profili, kullanıcı listesi, kullanıcı mail listesi yapımı",
    "22:11",
    true,
    false,
  ),
  MailModel(
    "Xiaomi Corporation",
    "Mi Account verification code",
    "Hi mktorunoglu55@gmail.com! \n\nYour Mi Account 61*****185 verification code is 844155. Don't show this code to other people. If you didn't request the code, go to id.mi.com and change your password immediately. This message was generated automatically. Don't reply to this message. \n\nMi Account team",
    "20:02",
    true,
    true,
  ),
  MailModel(
    "Xiaomi Corporation",
    "Mi Account verification code",
    "Hi mktorunoglu55@gmail.com! \n\nYour Mi Account 61*****185 verification code is 844155. Don't show this code to other people. If you didn't request the code, go to id.mi.com and change your password immediately. This message was generated automatically. Don't reply to this message. \n\nMi Account team",
    "20:02",
    true,
    true,
  ),
  MailModel(
    "Kevin Powell",
    "Day 8 - Conquering Responsive Layouts",
    "Hey there, \nWelcome to week 2 of Conquering Responsive Layouts! \nAs I mentioned at the end of week 1, what we covered was absolutely essential to understanding how to create responsive layouts. \n\nNow that we're getting more comfortable creating simple layouts that can adapt to any screen size (to a certain extent), it's time to up our game a little bit, and flexbox is the next key ingredient we are going to add to our arsenal! \n\nThis week, we'll be taking our layout, adding some new sections and a navigation to it, and using those things to help us really understand how flexbox works both in building out individual components as well bigger picture layouts. \n\nClick here to access today's lessons. \n\nKevin \n\nP.S. This week, the pace will be a little faster. If ever you feel like you're falling behind, please take it at your own pace and make sure you understand how things are working. The content of this course will be available to you forever!",
    "22:46",
    false,
    false,
  ),
  MailModel(
    "Yusuf Karahocagil (Jira)",
    "[JIRA] (WEB-35) Responsive olarak login, register, şifremi unuttum, kullanıcı profili, kullanıcı listesi, kullanıcı mail listesi yapımı",
    "Yusuf Karahocagil bir güncelleme yaptı. \n\nWebLessons	  /  	WEB-35 \n\nResponsive olarak login, register, şifremi unuttum, kullanıcı profili, kullanıcı listesi, kullanıcı mail listesi yapımı",
    "22:11",
    true,
    false,
  ),
];
